import { Geist, Geist_Mono, Nunito } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#5603AD] ${nunito.variable} `}
            >
                <header className="absolute top-0 z-50">
                    <nav className="flex items-center justify-between p-6 xl:py-8">
                        <div className="flex flex-1 flex-col items-center px-8">
                            <Image
                                src="logo-jva.svg"
                                alt="5191"
                                width="120"
                                height="120"
                            />
                        </div>
                    </nav>
                </header>
                <div className="fixed h-screen w-screen isolate overflow-hidden pt-14 grid items-center justify-center text-white/80">
                    <Image
                        alt="background image"
                        src={
                            "https://images.unsplash.com/photo-1598637529152-69afaa58432b?q=80&w=1169&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2830&q=80&blend=111827&sat=-50&exp=15&blend-mode=multiply"
                        }
                        fill
                        className="absolute inset-0 w-full h-full object-cover -z-10 opacity-80"
                    />
                    <div
                        aria-hidden="true"
                        className="absolute inset-x-0 -z-10 translate-z-0 overflow-hidden blur-3xl -top-80 opacity-40"
                    ></div>
                    {children}
                </div>
            </body>
        </html>
    );
}
